### ISSUE TITLE
data source cache_ds is not correctly configured, cause "Unable to load data from dataset" error in widgets using REST datasets

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#40]
the default cache data source (cache_ds) is configured with jndi, and is not working after installation
then it causes to have errors with REST datasets ("`Unable to load data from dataset <ds name> Please check dataset & widget config`" error in widgets using any REST dataset

I fixed the issue by configuring cache_ds using jdbc connection with the knowage db.

But the tomcat JNDI configuration should be aligned, with the jndi conf (java:comp/env/jdbc/cache_ds) from the database initial population

**Comment by kerny3d** [comment]
Fixed in:

https://github.com/KnowageLabs/Knowage-Server-Docker/commit/ba8358f7c4f37814755c1b23c2e558fa7bbbec2b

I've also updated the [docker-compose.yml](https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/Knowage-Server-Docker/docker-compose.yml) and [docker-swarm.yml](https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/Knowage-Server-Docker/docker-swarm.yml) descriptors if you want an example
