### ISSUE TITLE
Healthcheck url wich works

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#43]
Hello, in Dockerfile :

HEALTHCHECK --start-period=120s                                          \
            --interval=10s                                               \
            --timeout=5s                                                 \
            --retries=5                                                  \
            **CMD wget -q --spider http://127.0.0.1:8080/ || exit 1**

should be : 
HEALTHCHECK --start-period=120s                                          \
            --interval=10s                                               \
            --timeout=5s                                                 \
            --retries=5                                                  \
            **CMD wget -q --spider http://127.0.0.1:8080/knowage || exit 1**

**Comment by kerny3d** [comment]
Fixed in:

- Master: https://github.com/KnowageLabs/Knowage-Server-Docker/commit/e038ee7ba9aceae951e06b3c80c33ee07d7e7243
- knowage-server-7.4: https://github.com/KnowageLabs/Knowage-Server-Docker/commit/2baca9999ffc6988d871e371a2af80b770b7d20a
- knowage-server-7.2: https://github.com/KnowageLabs/Knowage-Server-Docker/commit/7f8016ff6a98f2bdc685688539b2e211b52b5c5d
