### ISSUE TITLE
Security vulnerabilities from AWS

### ISSUE THREAD

**Issue by qiaofeng1227** [KnowageLabs/Knowage-Server-Docker#46]
We use KnowageLabs/Knowage-Server-Docker, pubish konwage project on AWS.

![image](https://user-images.githubusercontent.com/43192516/116177948-51b0f400-a747-11eb-829d-43e420ad9d3e.png)

url:https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1938

Tomcat version is v8.5.37, please upgrade to Apache Tomcat 9.0.31、8.5.51.

**Comment by kerny3d** [comment]
Hi,

fixed in:

- https://github.com/KnowageLabs/Knowage-Server-Docker/commit/f355d35f4a406d5b4f35a9b0d08bf52356e9a902
- https://github.com/KnowageLabs/Knowage-Server-Docker/commit/175891e7323912aa9f7f872901a68cc2da0c6994

For the tag 8.0.0-SNAPSHOT, see: https://hub.docker.com/layers/knowagelabs/knowage-server-docker/8.0.0-SNAPSHOT/images/sha256-9424885093386c5c60c27482187a77656407a45cb4e2cfb5819c20d48c3efd83?context=explore

**Comment by chendelin1982** [comment]
Greate job!
