### ISSUE TITLE
JDBC URL error for cache db

### ISSUE THREAD

**Issue by DannieDarko** [KnowageLabs/Knowage-Server-Docker#61]
In script set-jndi-resources-for-mariadb-cache.sh the url is set to jdbc:maria:// although it needs to be jdbc:mariadb:// to select the correct driver

**Comment by kerny3d** [comment]
Hi DannieDarko,

I'm really sorry about that. I will immediately fix it.

**Comment by kerny3d** [comment]
Fixed in:
- master: https://github.com/KnowageLabs/Knowage-Server-Docker/commit/bc883c5264a470fe4f681e014ee00cc76f4868c6
- 8.1: https://github.com/KnowageLabs/Knowage-Server-Docker/commit/046f33848bcce18423f13fdd103a7a56544fb11a

The fixed images will be created by our CI/CD tool today.

Thank you for your report.
